package com.awstest.DynamoDbSpringBootDemo.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBDocument
public class Account {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String accountId;
    @DynamoDBAttribute
    private String accountNumber;
    @DynamoDBAttribute
    private String ownerName;
    @DynamoDBAttribute
    private double currentBalance;


}
