package com.awstest.DynamoDbSpringBootDemo.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.joda.time.DateTime;

import java.util.Date;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "Transaction")
public class Transaction {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute
    private Double transactionAmount;

    @DynamoDBAttribute
    private String sourceAccountId;

    @DynamoDBAttribute
    private String destinationAccountId;

    @DynamoDBAttribute
    private  Boolean wasSuccessful;

    @DynamoDBAttribute
    private Date date;

}

